#!/bin/bash

: 'Renames a target file based on arguments.
If the destination file name already exists, an 
index number is appended to the destination name.
'
echo "Running newname script..."

# Exception (1): Incorrect number of arguments
if [[ $# -ne 2 ]]
then
    echo "Error (1): Invalid number of arguments - expected 2, got $#."
    echo "2 arguments required: existing TARGET PATH followed by the DESTINATION PATH."
    exit
fi

# Get target path from argument 1
target=$1

# Exception (2): Target file does not exist.
if [[ ! -e "$target" ]]
then
    echo "Error (2): File \"$target\" does not exist in the current directory."
    exit
fi

# Get destination path from argument 2
destination=$2

# Check if destination path already exists
if [[ ! -e "$destination" ]]
then
    # Destination path does NOT exist, rename target file as normal.
    mv $target $destination

    if [ ! $? -eq 0 ]
    then
        echo "Error (3): mv command exited code $?."
        exit
    fi

    echo "File \"$target\" was successfully renamed to \"$destination\""
else
    : 'File name already exists. Increment and append the 
    index number to the destination path and check if that 
    name already exists. Iterates index until no matching file 
    is found, then renames the target file.
    '
    index=0
    new_path=$destination

    while [ -e $new_path ]
    do
        let index++
        new_path="$destination($index)"
    done

    echo "File \"$destination\" already exists:"

    mv $target $new_path

    if [ ! $? -eq 0 ]
    then
        echo "Error (4): mv command exited code $?."
        exit
    fi

    echo "\"$target\" was renamed to \"$new_path\"."
fi