#!/bin/bash

function run_organize() {
    echo "Running: $ bash organize $@"
    /bin/bash "organize" "$@"
}

# Recursively delete all subdirectories of the directory passed as $1
function clean_dir() {
    rm "-r" "$1"
}

if [[ $1 == "-c" ]]; then
    clean_dir "./data/"
    clean_dir "./grading"
fi

run_organize "./cis241.zip" "-v"
